- server/src/commandLine.mjs
Bug: Running "npm run dev" (vs. "npm run dev -- --triggers ./src/triggers") crashes because enabledTriggerPaths is null/undefined and not []. Fixed by ensuring this variable is always an array.
Also, don't show log message if no trigger directories have been specified.
> Fix bug if no trigger paths specified on command-line

- server/src/fireboltOpenRpc.mjs
Previously, validation was failing for optional parameters. This fix fixes that.
Example, SecondScreen.device(null) or SecondScreen.device() will now pass parameter validation.
> Fix parameter validation logic

- server/src/fireboltOpenRpc.mjs
- server/src/routes/api/meta.mjs
Hopefully fixes the validation bug for good.
- Looks for the required property in the right data structure (oParam)
- Always uses dereferenced metadata to ensure any/all $refs are resolved before validation
- Ensures the /api/v1/meta[?dereference=true] endpoint still works
Tested for all remaining parameter failures reported by QA team
> Fix bug with required params + always use dereferenced metadata

- server/package-lock.json
- server/package.json
- server/src/index.mjs
Use cors package to allow requests from other origins, e.g., from the firecert app or similar.
Issue originally reported and code fix supplied by Neerada Neelakantan.
> Add cors to allow requests from firecert app or similar

- server/package-lock.json
- server/package.json
- Moved from 0.6.0 to 0.6.1 for core
- Added "^" to pin to major version (0), meaning no more package.json updates till v1 (hopefully)
- Changed manage and discovery links to github links since we're not putting artifacts for those SDKs into npm for now
> Use ^0.6.1 for core and use github links for manage and discovery

- server/src/config.mjs
- server/src/fireboltOpenRpc.mjs
Support for mixed case module names in OpenRPC specification files and in JSON RPC messages at runtime
> Added support for mixed case module name

- server/src/fireboltOpenRpc.mjs
Support absolute path values for "fileName" in .mf.config.json files. This will allow a user to download an open rpc file and then provide a full absolute path to wherever she puts the file.
> Support absolute path open rpc files

- cli/examples/closed-captions-settings-reset.json
- cli/examples/closed-captions-settings.yaml
- server/src/events.mjs
- server/src/messageHandler.mjs
- server/src/routes/api/event.mjs
- server/src/stateManagement.mjs
- server/src/triggers/methodTriggers/closedcaptions.enabled/post.mjs
- Added ctx.set() and ctx.get() to ctx passed to pre- and post- triggers for both methods and events
- To do this, needed to export stateManagement.mjs::setScratch and ::getScratch
- These methods take userId, so needed to flow userId all the refactored methods in stateManagement.mjs
- Also needed to pass methodName to these refactored methods because it is used in error messages
- Added two example files, closed-captions-settings-reset.json and closed-captions-settings.yaml.
- Added one new example trigger in triggers/methodTriggers/closedcaptions.enabled/post.mjs
To test,
- Start Mock Firebolt using: npm run dev -- --manage --triggers ./src/triggers
- Note that this enables the manage sdk (so you can use ClosedCaptions.enabled(false|true)) and loads the above trigger (among others)
- …
> Scratch support plus bug fixes

- server/src/messageHandler.mjs
- server/src/proxyManagement.mjs
- server/test/suite/proxyManagement.test.mjs
Create 1-1 WS mapping instead of a singleton WS connection when MF is in proxy mode.
> SYSTEST-9250 1-1 WS Mapping for Proxy Mode

- functional/tests/core-manage-jsonrpc.test.mjs
- server/src/stateManagement.mjs
Ticket - https://ccp.sys.comcast.net/browse/SYSTEST-9348
As part of this ticket, implemented changes to support
- Allowing a "group" keyword to be passed for "scope" for all ctx.set(), ctx.get() and ctx.delete() functions
- When passed, the group of the userId that is INVOKING the YAML will be used as the "scope" for that call
- If the userId does not contain a group, a warning should be logged and full userId is used instead
> SYSTEST-9348-Use the word "group" as a shortcut for the user's group in ctx functions

- server/src/events.mjs
- server/src/messageHandler.mjs
- server/test/suite/events.test.mjs
**Background**
Mock Firebolt now supports multiple connections per user by utilizing an array/map of WS connections per userId.
This presents a problem for situations in which MF is tasked with triggering an event for a user. If a user is connected to MF with multiple connections, there is currently no way for MF to know which connection to send the requested event to.
In order to properly inject events, we must know which connection began listening to the requested event.
**Implementation**
MF already keeps track of which users are listening to which events. This is in order to support "sendEvent()" and "sendBroadcastEvent()" functionalities in YAML overrides as well as sending events manually using the --event CLI and its associated API. This same functionality can be extended to …
> SYSTEST-9338 - Send events to the WS object that subscribed to it

- cli/README.md
- docs/MFScope.md
- docs/UserGroups.md
- server/test/suite/stateManagement.test.mjs
- server/test/suite/userManagement.test.mjs
In several places in Mock Firebolt (Documentation, tests etc) there are references to real-world applications that might be used in MF (Ex: "netflix", "youtube"). As part of this ticket, 
- Removed references to non-Comcast applications inside of any Mock Firebolt code.
- Replaced such references with generic names
Ticket - https://ccp.sys.comcast.net/browse/SYSTEST-9379
> SYSTEST-9379-Remove branding references from MF

- docs/Events.md
- server/package-lock.json
- server/package.json
- server/src/.mf.config.SAMPLE.json
- server/src/events.mjs
- server/src/messageHandler.mjs
- server/src/proxyManagement.mjs
- server/test/suite/config.test.mjs
- server/test/suite/events.test.mjs
MF has the ability to trigger events either manually through the API/CLI or automatically through triggers.
In order to send and format these events, MF must keep track of which incoming users are listening. This formatting/searching/etc is currently hard-coded for the FB format. We must open up the existing event functionality to support any JsonRPC structure for events.
> Support JsonRPC structure for events - Part II

- README.md
- server/src/.mf.config.SAMPLE.json
- server/test/suite/config.test.mjs
This PR updates the url inside of .mf.SAMPLE.config.json so that users have access to the most updated openRPC file.
> Update openRPC URL to use latest version

- server/src/fireboltOpenRpc.mjs
- server/src/messageHandler.mjs
- server/src/routes/api/state.mjs
- server/test/suite/fireboltOpenRpc.test.mjs
Ticket - https://ccp.sys.comcast.net/browse/SYSTEST-9542
Changes made -
1. Added error handling for null/empty module/method in incoming MF requests
2. Got rid of the "toLowerCase()" function that just calls the native String "toLowerCase()
> SYSTEST-9542-Cannot read property 'toLowerCase' of undefined in mfos bug fix

- CHANGELOG.md
- Dockerfile
- README.md
- conduit/package-lock.json
- conduit/package.json
- docs/DotConfig.md
- docs/Overview.md
- docs/ProxyMode.md
- docs/Triggers.md
- docs/Versioning.md
- functional/package-lock.json
- functional/package.json
- functional/tests/utilities.mjs
- package-lock.json
- server/README.md
- server/package.json
- server/src/.mf.config.SAMPLE.json
- server/src/commandLine.mjs
- server/test/suite/config.test.mjs
- server/test/suite/sdkManagement.test.mjs
This pull request accomplishes the following:
* Removal of the firebolt-discovery-openrpc from the application
* Clean up of the script commands in server/package.json (clean, build, test, start)
* Use semantic versioning starting with v1.0.1
* Add versioning documentation and update changelog
* Update documentation
* Removes package-lock.json from the root directory
> Add Versioning to Mock Firebolt & Clean Up

- CHANGELOG.md
- cli/package.json
- conduit/package.json
- functional/package.json
- functional/tests/openRpcCall.test.mjs
- server/package.json
- server/src/events.mjs
- server/src/messageHandler.mjs
- server/src/routes/api/event.mjs
- server/test/suite/events.test.mjs
Bug fix for https://ccp.sys.comcast.net/browse/SYSTEST-9607
* New unit test to validate updated error handling function and functional test update to capture updated error message
* Refined `logErr()` and `fErr()` functions which handles event error messages to appropriately throw both event validation and event registration errors. 
* Fixed bug related to event error message handling wherein all event errors were previously thrown as an improper generic error which was misleading to users. Implemented a mechanism to correctly distinguish different types of event errors and throw them appropriately
> SYSTEST-9607- Event error message bug fix

- cli/examples/accessibility-closedCaptionsSettings.json
- cli/examples/accessibility-closedCaptionsSettings2.json
- cli/examples/accessibility-onVoiceGuidanceSettingsChanged1.event.json
- cli/examples/device-onNameChanged1.event.json
- cli/examples/lifecycle.yaml
- server/README.md
- server/src/changedConfigs.json
- server/src/config.mjs
- server/src/events.mjs
- server/src/fireboltOpenRpc.mjs
- server/src/messageHandler.mjs
- server/src/routes/api/state.mjs
- server/src/util.mjs
- server/test/suite/config.test.mjs
- server/test/suite/events.test.mjs
- server/test/suite/fireboltOpenRpc.test.mjs
Changes included:
1. allowMixedCase config was renamed to caseInsensitiveModules.
2. README entry was written for caseInsensitiveModules behavior.
3. caseInsensitiveModules was modified to only allow the module name to be case insensitive instead of the full method name to better represent the SDK itself.
4. Examples were modified to reflect the new behavior.
5. Additional check was added for events to address https://github.com/rdkcentral/mock-firebolt/issues/145. Which makes https://github.com/rdkcentral/mock-firebolt/pull/146 no longer needed.
6. Mapping was added in server/src/changedConfigs.json to allow backwards compatibility.
> Modify allowMixedCase behavior and config name.

- functional/package.json
- functional/tests/openRpcCall.test.mjs
- functional/tests/scope.test.mjs
- functional/tests/utilities.mjs
- server/src/userManagement.mjs
**Summary:**
This pull request introduces improvements to the existing WebSocket (ws) connection management and functional unit tests. Key changes include:
**WebSocket Connection Cleanup:** I've extended the current functionality that monitors and terminates stale ws connections. Now, when a ws connection is closed—whether due to inactivity or explicitly by a user—it's also removed from the _user2ws_ map. This map maintains a record of active ws connections for each user, ensuring the list remains accurate and up-to-date.
**Unit Test Refactoring:** A failing functional unit test caused by the above changes highlighted an issue where WebSocket connections were closed immediately after message receipt, hindering subsequent commands within the same test scenario. To address this, I …
> Remove stale ws connections from user2ws map when connection is closed

- server/src/messageHandler.mjs
Currently Mock Firebolt sends both an error message and a default response when a message with invalid params is sent to the server and validated. MF should only send back error message and should not send a default response as well.
> fix: Return only error message when invalid params are sent to mf

- server/src/configureAPI.mjs
- server/src/routes/api/bidirectional.mjs
Events, according to JSON-RPC spec, do not contain ID field in the payload.
> Bidirectional API for events
